### ISSUE TITLE
Is the project still alive - do you accept PRs ?

### ISSUE THREAD

**Issue by pierresouchay** [stusmall/consul-rust#33]
Hello,

I am an active OSS Consul contributor and maintain the diplomat and consul-templaterb libraries to interact with Consul.

I would like to create a Rust program interacting with Consul. I saw you crate that has a few issues, do you still accept PR to improve it or is it a dead project?

Will you consider PRs?

Regards

**Comment by stusmall** [comment]
I really want to thank you for reaching out.  For context for anyone else who sees this.  Pierre and I have been talking in private.  I took this project over sometime ago because we needed to get some fixes in but the maintainer had moved on.  I worked on this enough to get it in line to meet our needs and then unfortunately just couldn't find time to keep working on it.    I eventually just started ignoring PRs and issues as they came in.  I'm going to be stepping up and working on clearing out the backlog of issues and PRs and helping whip this in shape.
